### PR TITLE
Encode extrinsic call. fix #505

### LINKED ISSUE #505: The encoded hash in TaskTriggered does not contain the correct payload for XCM tasks
**Steps to Reproduce**
Take the task `4353492-0-1` on Turing Network as an example.

Run the below query in Insights,
```
SELECT block_height, id, timestamp, module, method, docs, data, extrinsic_id
FROM turing.events 
where data::text LIKE '%67gFKvqXtE5bx1E98uV6yhR9wosktNQQZyf5HdncHzvCqbUB%' AND module NOT IN ('balances','parachainStaking')
order BY block_height DESC;
```
You will see the TaskTriggered event, which contains the encodedCall
```
{'who': '67gFKvqXtE5bx1E98uV6yhR9wosktNQQZyf5HdncHzvCqbUB', 'taskId': '4353492-0-1', 'condition': {'type': 'time', 'timestamp': '1706074800'}, 'encodedCall': '0x1f00c60e71bd0f2e6d8832fea1a2d56091c48493c78801006808338e4789af9cef672b34662a6f74d0486439e4612aa5f4aa8b057f283a81c6de8aaf72cd471300008a5d78456301'}
```

**Expected vs. Actual Behavior**

The encodedCall `0x1f00c60e71bd0f2e6d8832fea1a2d56091c48493c78801006808338e4789af9cef672b34662a6f74d0486439e4612aa5f4aa8b057f283a81c6de8aaf72cd471300008a5d78456301` is not a hash that can be decoded by Turing. It is not the direct payload of the Turing task. Instead, it is the **XCM payload of task payload**. In this case, it is a hash on Moonriver, https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fmoonriver.api.onfinality.io%2Fpublic-ws#/extrinsics/decode

We expect the direct payload of the task in encodedCall,  one that can be decoded by Turing. Inside that payload, it contains the information of XCM, indicating the destination of the message. That’s how we will know that the XCM payload is for Moonriver, and then we can use Moonriver adapter to decode the inner encodedCall.

### PR DESCRIPTION
**Pull request by imstar15**
Update the TaskScheduled event by incorporating the encodedCall and excluding it from the TaskTriggered event.

1. Use the call parameter of scheduleDynamicDispatch as encodedCall.

2. Use the entire extrinsic of scheduleXcmpTask as encodedCall.

**Tests:**

Add `schedule_xcmp_task_and_check_encoded_call_success` test

**Manual testing:**

`TaskTriggered` event:

image

Decoded call:

image

### CODE REVIEW

File: pallets/automation-time/src/lib.rs [hunk 1]
```diff
@@ -411,32 +413,64 @@ pub mod pallet {
...
-				schedule_as,
 				instruction_sequence,
-			};
+				schedule_as,
+			}
+			.into();
+			let encoded_call = call.encode();
 
-			let schedule = schedule.validated_into::<T>()?;
+			Self::deposit_event(Event::<T>::TaskScheduled {
```
Comment (imstar15) [inline pallets/automation-time/src/lib.rs:467]: Deposit `TaskScheduled` event

File: pallets/automation-time/src/tests.rs [hunk 2]
```diff
@@ -1034,6 +1035,62 @@ fn schedule_xcmp_works() {
 	})
 }
 
+#[test]
+fn schedule_xcmp_task_and_check_encoded_call_success() {
```
Comment (imstar15) [inline pallets/automation-time/src/tests.rs:1039]: Add schedule_xcmp_task_and_check_encoded_call_success test

File: pallets/automation-time/src/lib.rs [hunk 3]
```diff
@@ -173,12 +174,13 @@ pub mod pallet {
 		type DelegatorActions: DelegatorActions<Self::AccountId, BalanceOf<Self>>;
 
 		/// The overarching call type.
-		type Call: Parameter
+		type RuntimeCall: Parameter
```
Comment (imstar15) [inline pallets/automation-time/src/lib.rs:177]: Rename `Call` to `RuntimeCall`.

File: pallets/automation-time/src/lib.rs [hunk 4]
```diff
@@ -173,12 +174,13 @@ pub mod pallet {
...
 			+ Dispatchable<RuntimeOrigin = Self::RuntimeOrigin, PostInfo = PostDispatchInfo>
 			+ GetDispatchInfo
 			+ From<frame_system::Call<Self>>
 			+ IsSubType<Call<Self>>
-			+ IsType<<Self as frame_system::Config>::RuntimeCall>;
+			+ IsType<<Self as frame_system::Config>::RuntimeCall>
+			+ From<crate::Call<Self>>;
```
Comment (imstar15) [inline pallets/automation-time/src/lib.rs:183]: Specify that `RuntimeCall` must implement the `From<crate::Call<Self>>` trait.

File: pallets/automation-time/src/lib.rs (hunk 3 above)
Comment (chrisli30) [reply pallets/automation-time/src/lib.rs:176]: What is the reason of this type re-definition?

**Review by chrisli30 — COMMENTED** [review]
The screenshot of the encoded call looks legit. I have left one comment. @v9n , could you double check the code?

**Comment by imstar15** [comment]
_What is the reason of this type re-definition?_

Related discussion:
https://github.com/paritytech/substrate/issues/11736#issuecomment-1163169701

PR:
https://github.com/paritytech/substrate/pull/11981

File: pallets/automation-time/src/benchmarking.rs [hunk 5]
```diff
@@ -217,18 +217,18 @@ benchmarks! {
 		let schedule = ScheduleParam::Fixed { execution_times: times };
 
 		let caller: T::AccountId = account("caller", 0, SEED);
-		let call: <T as Config>::Call = frame_system::Call::remark { remark: vec![] }.into();
+		let call: <T as Config>::RuntimeCall = frame_system::Call::remark { remark: vec![] }.into();
```
[the remark this answers is not in the document]
Comment (imstar15) [reply pallets/automation-time/src/benchmarking.rs:220]: I tried removing into() but encountered some errors.

```
error[E0308]: mismatched types
   --> pallets/automation-time/src/benchmarking.rs:220:42
    |
220 |         let call: <T as Config>::RuntimeCall = frame_system::Call::remark { remark: vec![] };
    |                   --------------------------   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected associated type, found `Call<_>`
    |                   |
    |                   expected due to this
    |
    = note: expected associated type `<T as pallet::Config>::RuntimeCall`
                          found enum `frame_system::Call<_>`
    = help: consider constraining the associated type `<T as pallet::Config>::RuntimeCall` to `frame_system::Call<_>` or calling a method that returns `<T as pallet::Config>::RuntimeCall`
    = note: for more information, visit https://doc.rust-lang.org/book/ch19-03-advanced-traits.html
help: call `Into::into` on this expression to convert `frame_system::Call<_>` into `<T as pallet::Config>::RuntimeCall`
    |
220 |         let call: <T as Config>::RuntimeCall = frame_system::Call::remark { remark: vec![] }.into();
    |                                                                                             +++++++

For more information about this error, try `rustc --explain E0308`.
error: could not compile `pallet-automation-time` (lib) due to previous error
```

What do you think the correct way to write it should be?

File: pallets/automation-time/src/lib.rs (hunk 1 above)
Comment (imstar15) [reply pallets/automation-time/src/lib.rs:466]: If we need to throw an event in the `validate_and_schedule_task` function, we should pass the pre-constructed `encoded_call` into the `validate_and_schedule_task` function.

This is because the `encoded_call` for `schedule_xcmp_task` needs to be constructed using the original function parameters and cannot be built within the `validate_and_schedule_task` function by using the `action` parameter passed to it.

That's why I opted to split `Self::deposit_event(Event::<T>::TaskScheduled { ... })` out this function.

Hi @chrisli30 , what are your thoughts on this?

File: pallets/automation-time/src/lib.rs [hunk 6]
```diff
@@ -411,32 +412,64 @@ pub mod pallet {
...
+				schedule_as,
+			}
+			.into();
+			let encoded_call = call.encode();
 
-			let schedule = schedule.validated_into::<T>()?;
+			Self::deposit_event(Event::<T>::TaskScheduled {
+				who,
+				task_id,
+				schedule_as: Self::get_schedule_as_from_action(action),
```
[the remark this answers is not in the document]
Comment (imstar15) [reply pallets/automation-time/src/lib.rs]: Yes, You're right. 👍
Fixed!

File: pallets/automation-time/src/lib.rs (hunk 1 above)
Comment (imstar15) [reply pallets/automation-time/src/lib.rs:466]: Okay!
However, the name "schedule_task" has already been used.
